services:
  db:
    image: postgres:15-alpine
    container_name: vitrine-tec-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=vitrinetec
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vitrine-tec-net

  minio:
    image: minio/minio:latest
    container_name: vitrine-tec-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=miniosupersecret
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - vitrine-tec-net

  app:
    build: .
    container_name: vitrine-tec-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vitrinetec
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=miniosupersecret
    networks:
      - vitrine-tec-net
    depends_on:
      - db
      - minio

volumes:
  postgres_data:
  minio_data:

networks:
  vitrine-tec-net:
    driver: bridge